# @package _global_
architectures:
  prior:
    _target_: code.architectures.base.DiagonalNormal
    z_dim: ${params.z_dim}
  latent_predictor:
    _target_: code.architectures.CMNIST.LatentClassifier
    layers: ${params.predictor.layers}
    dropout: ${params.predictor.dropout}
    z_dim: ${params.z_dim}
  encoder:
    _target_: code.architectures.CMNIST.ConvolutionalEncoder
    layers: ${params.encoder.layers}
    dropout: ${params.encoder.dropout}
    conv_flat_size: ${params.encoder.conv_flat_size}
    z_dim: ${params.z_dim}
  deterministic_encoder:
    _target_: code.architectures.CMNIST.ConvolutionalEncoder
    layers: ${params.encoder.layers}
    dropout: ${params.encoder.dropout}
    conv_flat_size: ${params.encoder.conv_flat_size}
    z_dim: ${params.z_dim}
    posterior: Delta
  predictor:
    _target_: code.architectures.utils.SequentialModel
    models:
      - ${architectures.deterministic_encoder}
      - ${architectures.latent_predictor}
  discriminator:
    _target_: code.architectures.CMNIST.Discriminator
    layers: ${params.discriminator.layers}
    dropout: ${params.discriminator.dropout}
    spectral_norm : ${params.discriminator.spectral_norm}
    z_dim: ${params.z_dim}
  joint_discriminator:
    _target_: code.architectures.CMNIST.JointDiscriminator
    layers: ${params.discriminator.layers}
    dropout: ${params.discriminator.dropout}
    spectral_norm: ${params.discriminator.spectral_norm}
    z_dim: ${params.z_dim}

# hyper-parameters for the architectures
params:
  z_dim: 64
  beta: 0.1
  lr: 1e-4
  disc_lr: 1e-4
  batch_size: 256
  encoder:
    layers:
      - in_channels: 2
        out_channels: 32
        kernel_size: 5
        stride: 2
      - in_channels: 32
        out_channels: 64
        kernel_size: 5
        stride: 2
      - in_channels: 64
        out_channels: 128
        kernel_size: 4
    dropout: 0.25
    conv_flat_size: 128
  predictor:
    layers: [1024, 128]
    dropout: 0
  discriminator:
    layers: [1024, 128]
    dropout: 0
    spectral_norm: True
  n_adversarial_steps: 10

