# @package _global_
defaults:
  - /optimization: batch_ADAM_schedule

model:
  _target_: src.models.VIB
  prior: ${architectures.prior}
  latent_predictor: ${architectures.latent_predictor}
  encoder: ${architectures.encoder}
  beta: ${params.beta}

# Scheduler to determine the regularization strength while the model is training
beta_scheduler:
  _target_: src.utils.schedulers.LinearIncrementScheduler
  start_value: 0.00001
  start_iteration: 5000
  increment_by: 0.00005