# @package _global_
trainer:
  checkpoint_callback: False
  auto_select_gpus: ${device.auto_select_gpus}
  logger:
    _target_: framework.logging.WandbLogger
    project: ${run.project}
    name: ${run.name}
    save_dir: ${run.dir}
callbacks:
  - _target_: framework.callbacks.checkpoints.WandbModelCheckpoint
    save_last: true
  - _target_: framework.callbacks.TrainDurationCallback
    train_for: ${train_for}


