Accuracy/Train(t=1):
  evaluate_every: 1000 iterations
  evaluator:
    _target_: code.evaluation.AccuracyEvaluation
    evaluate_on: train
    n_samples: 2048
Accuracy/Train(t=0):
  evaluate_every: 1000 iterations
  evaluator:
    _target_: code.evaluation.AccuracyEvaluation
    evaluate_on: train_t0
    n_samples: 2048
Accuracy/Test(t=0):
  evaluate_every: 1000 iterations
  evaluator:
    _target_: code.evaluation.AccuracyEvaluation
    evaluate_on: test
    n_samples: 2048
Accuracy/Test(t=1):
  evaluate_every: 1000 iterations
  evaluator:
    _target_: code.evaluation.AccuracyEvaluation
    evaluate_on: test_t1
    n_samples: 2048