# @package _global_

callbacks:
  - _target_: code.callbacks.EvaluationCallback
    name: Accuracy/Train(t=1)
    evaluate_every: 1000 iterations
    evaluator:
      _target_: code.evaluation.AccuracyEvaluation
      evaluate_on: train
      n_samples: 2048
  - _target_: code.callbacks.EvaluationCallback
    name: Accuracy/Train(t=0)
    evaluate_every: 1000 iterations
    evaluator:
      _target_: code.evaluation.AccuracyEvaluation
      evaluate_on: train_t0
      n_samples: 2048
  - _target_: code.callbacks.EvaluationCallback
    name: Accuracy/Test(t=0)
    evaluate_every: 1000 iterations
    evaluator:
      _target_: code.evaluation.AccuracyEvaluation
      evaluate_on: test
      n_samples: 2048
  - _target_: code.callbacks.EvaluationCallback
    name: Accuracy/Test(t=1)
    evaluate_every: 1000 iterations
    evaluator:
      _target_: code.evaluation.AccuracyEvaluation
      evaluate_on: test_t1
      n_samples: 2048
  - _target_: code.callbacks.EvaluationCallback
    name: CrossEntropy/Train(t=1)
    evaluate_every: 1000 iterations
    evaluator:
      _target_: code.evaluation.CrossEntropyEvaluation
      evaluate_on: train
      n_samples: 10000
  - _target_: code.callbacks.EvaluationCallback
    name: CrossEntropy/Train(t=0)
    evaluate_every: 1000 iterations
    evaluator:
      _target_: code.evaluation.CrossEntropyEvaluation
      evaluate_on: train_t0
      n_samples: 10000
  - _target_: code.callbacks.EvaluationCallback
    name: CrossEntropy/Test(t=0)
    evaluate_every: 1000 iterations
    evaluator:
      _target_: code.evaluation.CrossEntropyEvaluation
      evaluate_on: test
      n_samples: 10000
  - _target_: code.callbacks.EvaluationCallback
    name: CrossEntropy/Test(t=1)
    evaluate_every: 1000 iterations
    evaluator:
      _target_: code.evaluation.CrossEntropyEvaluation
      evaluate_on: test_t1
      n_samples: 10000