defaults:
  - device: ${oc.env:DEVICE_NAME}
  - logging: wandb

callbacks: []

trainer:
  _target_: pytorch_lightning.Trainer
  gpus: ${device.gpus}

run:
  name: null
  dir: ${device.experiments_root}/experiments/${now:%Y-%m-%d}/${now:%H-%M-%S}
  project: noname

hydra:
  run:
    dir: ${run.dir}