defaults:
  - logging: wandb
  - device: ${oc.env:DEVICE_NAME}
  - data: CMNIST
  - architectures: MLP
  - model: VIB
  - evaluation:
      - accuracy
      - cross-entropy

train_for: 100 epochs

trainer:
  _target_: pytorch_lightning.Trainer
  gpus: ${device.gpus}
  max_epochs: 100000

seed: 42

run:
  name: null
  dir: ${device.experiments_root}/experiments/${now:%Y-%m-%d}/${now:%H-%M-%S}
  project: noname

hydra:
  run:
    dir: ${run.dir}