_target_: code.optimization.AdamBatchRegularizedOptimization

model: ${model}
data: ${data}
lr: ${params.lr}
num_workers: ${device.num_workers}
batch_size: ${params.batch_size}
beta_scheduler: ${beta_scheduler}